### ISSUE TITLE
Demo on the website is broken

### ISSUE THREAD

**Issue by yktoo** [wolfgang42/yaml-multiline#12]
Nothing seems to happen when I click the controls anymore. I tried in latest Chrome and Firefox.
![yaml-multiline](https://user-images.githubusercontent.com/1675911/101337157-a11b8400-387b-11eb-8aa9-9251ad6a7acf.gif)

**Comment by wolfgang42** [comment]
Oops, thanks for reporting this. I made what I thought was an innocuous change to the build settings and accidentally caused it to strip out all the CSS for the interactive parts. Should be fixed now.
