### ISSUE TITLE
Example sentences

### ISSUE THREAD

**Issue by gitqlt** [wolfgang42/yaml-multiline#13]
The Flow scalars/Single-quoted example constructs the sentence: (Here I only use the pure sentence, without the demonstrative quotation marks, etc...)

`Several lines of text, containing single quotes... Escapes ... whitespace on lines is ignored.`

So I think: What about the double quotes? The sentence might suggest that it is better not to use double quotes here.
Which is false. Please use double quote(s) in this example (and vice versa).

PS: Thanks for putting this site together, it's perfect. Thank you for your work.

**Comment by wolfgang42** [comment]
How does this look?

```yaml
example: 'Several lines of text,
  containing ''single quotes'' and "double quotes". Escapes (like \n) don''t do anything.
  
  Newlines can be added by leaving a blank line.
    Leading whitespace on lines is ignored.'
```
```yaml
example: "Several lines of text,\n
  containing \"double quotes\" and 'single quotes'. Escapes (like \\n) work.\nIn addition,
  newlines can be esc\
  aped to prevent them from being converted to a space.
  
  Newlines can also be added by leaving a blank line.
    Leading whitespace on lines is ignored."
```

**Comment by gitqlt** [comment]
This is fine. What we're looking for next is a page with similarly clear examples of anchors, aliases, merge

**Comment by wolfgang42** [comment]
Excellent! I'll make sure to include this change in the next update when I get around to it.

Yeah, I'd also like to make a more extensive YAML guide. It takes time to wrap my head around everything and figure out how to explain it clearly, though, so I'm unlikely to add anything soon.
