### ISSUE TITLE
not an issue, just wanted to say thanks

### ISSUE THREAD

**Issue by siddacious** [wolfgang42/yaml-multiline#4]
Good morning :)

Thanks for putting this site together, it's _perfect_. Just the info I needed, nothing else and clearly presented. Thank you for your work.
-B

**Comment by siddacious** [comment]
(closing because I'm just using issues as a messaging service 😬)

**Comment by chipzoller** [comment]
Wanted to also convey my thanks @wolfgang42 (yes, I know this is closed, but since Discussions aren't enabled wanted to let you know your work is appreciated)

**Comment by wolfgang42** [comment]
The issue may be closed, but I’m still subscribed to it :) Glad to hear people are finding the site useful!
