### ISSUE TITLE
Single-quoted and double-quoted examples are incorrect

### ISSUE THREAD

**Issue by eemeli** [wolfgang42/yaml-multiline#5]
The single-quoted and double-quoted examples do not have sufficient indentation, as they imply that in a block mapping a quoted scalar value can continue from the same column as its key. These values need to in fact be indented at least one space more than that, as is done with the plain scalar example.

This is mentioned in [section 8.2.3](https://yaml.org/spec/1.2/spec.html#id2799181) of the YAML 1.2 spec.

This issue was originally raised as eemeli/yaml#176 by @erunion.

**Comment by wolfgang42** [comment]
Thanks for reporting! I've just corrected the doc. My source material has this right, I'm not sure how I managed to mess it up.
