### ISSUE TITLE
Page layout & texts improvement proposal

### ISSUE THREAD

**Issue by osher** [wolfgang42/yaml-multiline#7]
Hi,

I think this page is a great initiative, however, despite me using it for years - it appears that I have missed important parts of it's message, and many others with me.

The point where I noted it is after the following issue:
https://github.com/containous/traefik/issues/7074

After a correspondence with a friend of mine (which happens to be a co-author of the standard) - I think I figured how could it be that people miss it: 

The first title is more dominant than the paragraph before it, which caused me and some other people to skip to the first title and miss it... - resulting with attempts to use the more complex types where a simple scalar would work just enough.

I'd propose to start directly with a title, like so:

---

> ## Two Types of Formats for Strings
> 
> There are two types of formats that YAML supports for scalar strings.  (Scalars are what YAML calls basic values like numbers or strings, as opposed to complex types like arrays or objects).
>  - _**flow scalar formats**_ -  these are designed for robust simplicity but do have a limited escaping and line-break support. They are designed to ignore indentations.
>  - _**block scalar formats**_ - these provide more control over how they are interpreted by increasing sensitivity rules regarding indentations and escaping. These are designed to answer for cases whenever scalar flow formats become cumbersome or insufficient.
> 
> Although they are parsed by different rules - they all express strings, allowing authors to choose the option that expresses best what they need the string to be. 
> 

---
As you see - it's heavily based on your original text, just layed out differently, to rutn the important things into eye-catcher for page skimmers (which, sadly lets face it - gets to be the dominant form of reading).

I'd also swap the block and scalar examples.

mm. I also tend to think that it would add to clarity if the text starts from the trivial example of a non-quoted single-line scalar string, and single-line quoted string.

Yes, I know the page is called multiline strings, but this explain the narrative of escalating needs of more complex user-cases, as opposed to the design goal of robust simplicity, and their answer in YAML

LMK If you'd like any of these proposals - I'll translate it to a PR 👍 

Keep up the great work! 👍

**Comment by Moulick** [comment]
I agree with @osher, I also missed the the first paragraph

**Comment by wolfgang42** [comment]
Yes, these changes look great! I’ve always been vaguely dissatisfied with the way I wrote that first paragraph and laid out the page, but not enough to be able to figure out how to fix it. It’s hard to find these sorts of problems as the author of a document, since writing it gives you all sorts of blind spots for where the problems are.

Sorry for taking so long to notice this. I'll gladly accept a PR for everything you suggested changing, or if you don’t get around to making one I’ll incorporate your changes and make sure to credit you next time I get around to doing another update.

**Comment by wolfgang42** [comment]
Thanks again for your suggestions! I finally got around to merging them, please do let me know if you see more places to improve!
